---
title: "FA6"
author: "Gabriel Tagaytay"
date: "`r Sys.Date()`"
output:
  pdf_document:
    latex_engine: xelatex
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# I. Geometric Distribution  

## 1. Set the probability of success
```{r}
p <- 0.2
```

## 2. Generate 1000 random variables from the geometric distribution
```{r}
set.seed(123)  # For reproducibility
x <- rgeom(1000, prob = p) + 1  # Adding 1 since R's rgeom() gives (failures before first success)
```

## 3. Calculate basic statistics
```{r}
mean_x <- mean(x)
var_x <- var(x)
sd_x <- sd(x)
```

## 4. Print the results with specified format
```{r}
cat("Number of trials required to achieve first success:\n")
cat(sprintf("Mean (in 2 decimal places): %.2f\n", mean_x))
cat(sprintf("Variance (in 2 decimal places): %.2f\n", var_x))
cat(sprintf("Standard deviation (in 2 decimal places): %.2f\n", sd_x))
```

## 5. Plot the histogram
```{r}
hist(x, breaks = 30, col = "lightblue", main = "Histogram of Geometric Distribution", xlab = "Number of Trials", ylab = "Frequency")
```

# II. Hypergeometric Distribution
## Given data
```{r}
total_defective_40 <- 0.1 * 40  # Number of defective chips in a box of 40
total_defective_5000 <- 0.1 * 5000  # Number of defective chips in a box of 5000
sample_size <- 10  # Sample size
threshold <- 10 * 0.1  # More than 10% defectives (i.e., more than 1 defective)
```

## Compute probability for a box of 40
```{r}
prob_40 <- 1 - phyper(threshold, total_defective_40, 40 - total_defective_40, sample_size)
```

## Compute probability for a box of 5000
```{r}
prob_5000 <- 1 - phyper(threshold, total_defective_5000, 5000 - total_defective_5000, sample_size)
```

## Print results
```{r}
cat("Probability for a box of 40:", round(prob_40, 4) * 100, "%\n")
cat("Probability for a box of 5000:", round(prob_5000, 4) * 100, "%\n")
```


[CLICK HERE TO VIEW THE R MARKDOWN FILE ON GITHUB!!!](https://github.com/gabriyeeel/Formattive-Assessments-Files/blob/main/FA6.Rmd)
